### ISSUE TITLE
Multi-insert

### ISSUE THREAD

**Issue by mfahlsing** [jimmysole/qbc-program#2]
https://github.com/jimmysole/qbc-program/blob/31a846f3f575e9dd31ba53b005e28120ae954e52/QBC/Form1.cs#L279

I'm having trouble following some of the code since I'm not 100% familiar with the C# syntax for some things. But it seems you want to build a multi-insert here. That would look something like:

```
INSERT INTO MyTable (Col1, Col2, Col3)
VALUES
('Val1', 'Val2', 'Val3'),
('Thing1, 'Thing2, 'Thing3');
```

With the @param syntax
```
INSERT INTO MyTable (Col1, Col2, Col3)
VALUES
(@ChildForm1Val1, @ChildForm1Val2, @ChildForm1Val3),
(@ChildForm2Val1, @ChildForm2Val2, @ChildForm2Val3');
```
So I think you have to build the SQL differently (this way) and then bind the child form fields properly

**Comment by jimmysole** [comment]
yeah. trying to insert more than one children values but the column names are being duplicated (in the insert query syntax), and it's bugging out

**Comment by mfahlsing** [comment]
It probably has something to do with how you are trying to dynamically build that based on the form field definitions. Bit the bullet and write the entire thing out, similar to the other queries. Once you get that working properly, especially with the binding, you can then try and refactor it to be dynamic.

Post a sample of the raw SQL query it builds and I might be able to help pinpoint where the issue is.
